### ISSUE TITLE
不好意思

### ISSUE THREAD

**Issue by tonyqus** [88250/88250#3]
麻烦问你一下，[刘怡](https://github.com/alexinea)是在你们公司吗？

**Comment by tonyqus** [comment]
我先自我介绍下，免得引起误会。

我是非常资深的.NET开发者，有18年的软件开发经验，我创建的NPOI项目是中国区最优秀的.NET项目之一，目前nuget下载量3100万。我长期活跃在中国.NET开发社区，我也是.NET基金会成员，前微软最有价值专家。

我大概是在2020年因为刘怡所在的[开源组织NCC](http://dotnetcore.xyz/)偷我的开源项目，然后我就去微软投诉了。结果就遭到了这个组织成员的疯狂报复和霸凌，甚至搞到我当时所在的单位iHerb，太流氓这帮人，简直就是社区毒瘤。

刘怡是这个组织的主要负责人，基本是大管家的角色。他一直不愿意承认自己做的任何事。

比如通过[Dotnetcore.npoi的readme](https://github.com/dotnetcore/NPOI/blob/master/README.zh-CN.md)造谣诽谤我和我的开源项目，很多说的就根本不是事实。

我大概在2021年在社区里对他们进行了揭发，写了一篇博文[《起底开源邪教NCC组织》](https://zhuanlan.zhihu.com/p/626835710)。至此，社区开始认识到这个组织的危害，一切才逐步告一段落。

但其实我一直在跟踪所有NCC成员的动向，防止他们再次耍流氓、危害社区，这其中包括刘怡。

刘怡是上海人，说起来他还是我学弟，因为我两都毕业于上海师范大学计算机系，在霸凌事件之前我和他完全不认识。

**Comment by 88250** [comment]
你好，我不认识他。

**Comment by tonyqus** [comment]
好的，打扰了
